# -*- coding: utf-8 -*-
from __future__ import unicode_literals
"""
Python 3.6.8
更新：2019-12-23
日级别监控代码
"""

import uku_new_model_v4.var_sql as uku_newmodelv4_var_sql
import uku_iosnewmodel_v1.var_sql as uku_iosnewmodelv1_var_sql
import uku_new_model_v5.var_sql as uku_newmodelv5_var_sql
import uku_oldmodel_v2.var_sql as uku_oldmodelv2_var_sql
import uku_new_model_v5.var_sql_loan as uku_newmodelv5_var_sql_loan
import uku_new_model_v6.var_sql as uku_newmodelv6_var_sql
import uku_oldmodel_v3.var_sql as uku_oldmodelv3_var_sql

MODEL_CONFIG = {"UKU_A_IOSNEWMODELV1": {'product_name': 'uku',
                                        'model_name': 'iosnewusermodelv1',
                                        'daily_param': {'obs_window': 30,
                                                        'per_window': 0,
                                                        'time_type': 'day',
                                                        'sql': uku_iosnewmodelv1_var_sql.VAR_SQL,
                                                        'recipients': ['huangweijie@huojintech.com']},
                                        'weekly_param': {'obs_window': 4,
                                                         'per_window': 0,
                                                         'time_type': 'week',
                                                         'sql': uku_iosnewmodelv1_var_sql.VAR_SQL,
                                                         'recipients': ['huangweijie@huojintech.com']},
                                        'performance_param': {'obs_window': 4,
                                                              'per_window': 21,
                                                              'time_type': 'week',
                                                              'sql': uku_iosnewmodelv1_var_sql.PER_SQL,
                                                              'time_cols': 'effective_date',
                                                              'flag': 'flag_7',
                                                              'label': 'dpd7+',
                                                              'recipients': ['huangweijie@huojintech.com']},
                                        'file_name': '/home/ops/repos/analysis/cron/alert/excel/UKU_IOSModelV1.xlsx',
                                        'report_path': '/home/ops/repos/analysis/cron/alert/excel/daily_report/uku_iosnewmodel_v1/',
                                        'eda_name': '02_EDA',
                                        'dist_name': '03_distribution',
                                        'perftable_name': '04_performance',
                                        },
                "UKU_A_LINKAGA_NEWMODELV1": {'product_name': 'linkaja',
                                             'model_name': 'linkaja_newusermodelv1',
                                             'daily_param': {'obs_window': 30,
                                                             'per_window': 0,
                                                             'time_type': 'day',
                                                             'sql': uku_iosnewmodelv1_var_sql.VAR_SQL,
                                                             'recipients': ['huangweijie@huojintech.com']},
                                             'weekly_param': {'obs_window': 4,
                                                              'per_window': 0,
                                                              'time_type': 'week',
                                                              'sql': uku_iosnewmodelv1_var_sql.VAR_SQL,
                                                              'recipients': ['huangweijie@huojintech.com']},
                                             'performance_param': {'obs_window': 4,
                                                                   'per_window': 34,
                                                                   'time_type': 'week',
                                                                   'sql': uku_iosnewmodelv1_var_sql.PER_SQL,
                                                                   'time_cols': 'effective_date',
                                                                   'flag': 'flag_7',
                                                                   'label': 'dpd7+',
                                                                   'recipients': ['huangweijie@huojintech.com']},
                                             'file_name': '/home/ops/repos/analysis/cron/alert/excel/UKU_IOSModelV1.xlsx',
                                             'report_path': '/home/ops/repos/analysis/cron/alert/excel/daily_report/uku_iosnewmodel_v1/',
                                             'eda_name': '02_EDA',
                                             'dist_name': '03_distribution',
                                             'perftable_name': '04_performance',
                                             },
                "UKU_A_OLDMODELV2": {'product_name': 'uku',
                                     'model_name': 'oldusermodelv2',
                                     'daily_param': {'obs_window': 30,
                                                     'per_window': 0,
                                                     'time_type': 'day',
                                                     'sql': uku_oldmodelv2_var_sql.VAR_SQL,
                                                     'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com']
                                                     },
                                     'weekly_param': {'obs_window': 4,
                                                      'per_window': 0,
                                                      'time_type': 'week',
                                                      'sql': uku_oldmodelv2_var_sql.VAR_SQL,
                                                      'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com']
                                                      },
                                     'performance_param': {'obs_window': 15,
                                                           'per_window': 21,
                                                           'time_type': 'day',
                                                           'sql': uku_oldmodelv2_var_sql.PER_SQL,
                                                           'time_cols': 'effective_date',
                                                           'flag': 'ever7',
                                                           'label': 'dpd7+',
                                                           'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com']
                                                           },
                                     'file_name': '/home/ops/repos/analysis/cron/alert/excel/UKU_OldUserModelV2.xlsx',
                                     'report_path': '/home/ops/repos/analysis/cron/alert/excel/eda/uku_old_model_v2/',
                                     'eda_name': '02_EDA_ONEKEYLOAN',
                                     'dist_name': '03_distribution_ONEKEYLOAN',
                                     'perftable_name': '04_performance',
                                     },
                "UKU_A_NEWMODELV5": {'product_name': 'uku',
                                     'model_name': 'newusermodelv5',
                                     'daily_param': {'obs_window': 30,
                                                     'per_window': 0,
                                                     'time_type': 'day',
                                                     'sql': uku_newmodelv5_var_sql.VAR_SQL,
                                                     'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com']
                                                     },
                                     'weekly_param': {'obs_window': 4,
                                                      'per_window': 0,
                                                      'time_type': 'week',
                                                      'sql': uku_newmodelv5_var_sql.VAR_SQL,
                                                      'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com']
                                                      },
                                     'performance_param': {
                                         'obs_window': 4,
                                         'per_window': 21,
                                         'time_type': 'week',
                                         'sql': uku_newmodelv5_var_sql.PER_SQL,
                                         'time_cols': 'effective_date',
                                         'flag': 'flag7',
                                         'label': 'dpd7+',
                                         'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com']
                                     },
                                     'file_name': '/home/ops/repos/analysis/cron/alert/excel/UKU_NewUserModelV5.xlsx',
                                     'report_path': '/home/ops/repos/analysis/cron/alert/excel/daily_report/uku_new_model_v5/',
                                     'eda_name': '02_EDA',
                                     'dist_name': '03_distribution',
                                     'perftable_name': '04_performance'
                                     #'app_list_high':'/home/ops/repos/analysis/cron/alert/excel/high_freq_list.txt',
                                     #'app_list_mid':'/home/ops/repos/analysis/cron/alert/excel/mid_freq_list.txt',
                                     #'app_list_low':'/home/ops/repos/analysis/cron/alert/excel/low_freq_list.txt'
                                     },
                "UKU_A_NEWMODELV5_LOAN": {'product_name': 'uku-loan',
                                          'model_name': 'newusermodelv5',
                                          'daily_param': {'obs_window': 30,
                                                          'per_window': 0,
                                                          'time_type': 'day',
                                                          'sql': uku_newmodelv5_var_sql_loan.VAR_SQL,
                                                          'recipients': ['jiangshanjiao@mintechai.com']
                                                          },
                                          'file_name': '/home/ops/repos/analysis/cron/alert/excel/UKU_NewUserModelV5.xlsx',
                                          'report_path': '/home/ops/repos/analysis/cron/alert/excel/daily_report/uku_new_model_v5/',
                                          'eda_name': '06_loanEDA',
                                          'dist_name': '05_loandistribution',
                                          'perftable_name': '04_performance',
                                          'app_list_high': '/home/ops/repos/analysis/cron/alert/excel/high_freq_list.txt',
                                          'app_list_mid': '/home/ops/repos/analysis/cron/alert/excel/mid_freq_list.txt',
                                          'app_list_low': '/home/ops/repos/analysis/cron/alert/excel/low_freq_list.txt'
                                          },
                "UKU_A_NEWMODELV6": {'product_name': 'uku',
                                     'model_name': 'newusermodelv6',
                                     'daily_param': {'obs_window': 30,
                                                     'per_window': 0,
                                                     'time_type': 'day',
                                                     'sql': uku_newmodelv6_var_sql.VAR_SQL,
                                                     'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com']
                                                     },
                                     'weekly_param': {'obs_window': 4,
                                                      'per_window': 0,
                                                      'time_type': 'week',
                                                      'sql': uku_newmodelv6_var_sql.WEEKLY_VAR_SQL,
                                                      'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com']
                                                      },
                                     'performance_param': {
                                         'obs_window': 4,
                                         'per_window': 21,
                                         'time_type': 'week',
                                         'sql': uku_newmodelv6_var_sql.PER_SQL,
                                         'time_cols': 'effective_date',
                                         'flag': 'flag7',
                                         'label': 'dpd7+',
                                         'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com']
                                     },
                                     'file_name': '/home/ops/repos/analysis/cron/alert/excel/UKU_NewUserModelV6.xlsx',
                                     'report_path': '/home/ops/repos/analysis/cron/alert/excel/daily_report/uku_new_model_v6/',
                                     'eda_name': '02_EDA',
                                     'dist_name': '03_distribution',
                                     'perftable_name': '04_performance'
                                     },
                "UKU_A_OLDMODELV3": {'product_name': 'uku',
                                     'model_name': 'oldusermodelv3',
                                     'daily_param': {'obs_window': 30,
                                                     'per_window': 0,
                                                     'time_type': 'day',
                                                     'sql': uku_oldmodelv3_var_sql.VAR_SQL,
                                                     'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com', 'xuchao1@huojintech.com']
                                                     },
                                     'weekly_param': {'obs_window': 4,
                                                      'per_window': 0,
                                                      'time_type': 'week',
                                                      'sql': uku_oldmodelv3_var_sql.VAR_SQL,
                                                      'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com', 'xuchao1@huojintech.com']
                                                      },
                                     'performance_param': {'obs_window': 15,
                                                           'per_window': 21,
                                                           'time_type': 'day',
                                                           'sql': uku_oldmodelv3_var_sql.PER_SQL,
                                                           'time_cols': 'effective_date',
                                                           'flag': 'ever7',
                                                           'label': 'dpd7+',
                                                           'recipients': ['jiangshanjiao@mintechai.com', 'yantingting@mintechai.com', 'xuchao1@huojintech.com']
                                                           },
                                     'file_name': '/home/ops/repos/analysis/cron/alert/excel/UKU_OldUserModelV3.xlsx',
                                     'report_path': '/home/ops/repos/analysis/cron/alert/excel/eda/uku_old_model_v3/',
                                     'eda_name': '02_EDA',
                                     'dist_name': '03_distribution',
                                     'perftable_name': '04_performance',
                                     }
                }

#
# '''
#         "CASHCASH_A_NEWMODELV5": {'product_name' :'cashcash',
#                     'model_name' : 'newusermodelv5',
#                     'daily_param': {'obs_window': 40,
#                                     'per_window': 0,
#                                     'time_type': 'day',
#                                     'sql': uku_newmodelv5_var_sql.VAR_SQL,
#                                     'recipients': ['jiangshanjiao@mintechai.com']
#                                   },
#                     'weekly_param': {'obs_window': 4,
#                                      'per_window': 0,
#                                      'time_type': 'week',
#                                      'sql': uku_newmodelv5_var_sql.VAR_SQL,
#                                      'recipients': ['jiangshanjiao@mintechai.com']
#                                     },
#                     'performance_param': {
#                                     'obs_window': 15,
#                                     'per_window': 21,
#                                     'time_type': 'day',
#                                     'sql': uku_newmodelv5_var_sql.PER_SQL,
#                                     'time_cols': 'effective_date',
#                                     'flag': 'flag7',
#                                     'label': 'dpd7+',
#                                     'recipients': ['jiangshanjiao@mintechai.com']
#                                 },
#                     'file_name': '/home/ops/repos/analysis/cron/alert/excel/UKU_NewUserModelV5.xlsx',
#                     'report_path': '/home/ops/repos/analysis/cron/alert/excel/daily_report/uku_new_model_v5/',
#                     'eda_name': '02_EDA',
#                     'dist_name': '03_distribution',
#                     'perftable_name': '04_performance',
#                     'app_list_high':'/home/ops/repos/analysis/cron/alert/excel/high_freq_list.txt',
#                     'app_list_mid':'/home/ops/repos/analysis/cron/alert/excel/mid_freq_list.txt',
#                     'app_list_low':'/home/ops/repos/analysis/cron/alert/excel/low_freq_list.txt'
#                 },
#         "CASHCASH_A_NEWMODELV5_LOAN": {'product_name' :'cashcash-loan',
#                     'model_name' : 'newusermodelv5',
#                     'daily_param': {'obs_window': 5,
#                                     'per_window': 0,
#                                     'time_type': 'day',
#                                     'sql': uku_newmodelv5_var_sql_loan.cash_SQL,
#                                     'recipients': ['jiangshanjiao@mintechai.com']
#                                   },
#                     'file_name': '/home/ops/repos/analysis/cron/alert/excel/UKU_NewUserModelV5.xlsx',
#                     'report_path': '/home/ops/repos/analysis/cron/alert/excel/daily_report/uku_new_model_v5/',
#                     'eda_name': '06_loanEDA',
#                     'dist_name': '07_cashcash_loandistribution',
#                     'perftable_name': '04_performance',
#                     'app_list_high':'/home/ops/repos/analysis/cron/alert/excel/high_freq_list.txt',
#                     'app_list_mid':'/home/ops/repos/analysis/cron/alert/excel/mid_freq_list.txt',
#                     'app_list_low':'/home/ops/repos/analysis/cron/alert/excel/low_freq_list.txt'
#                 },
#                         "UKU_A_OLDMODELV2_ONEKEYLOAN": {'product_name' :'uku_onekyloan',
#                     'model_name' : 'oldusermodelv2',
#                     'daily_param': {'obs_window': 30,
#                                     'per_window': 0,
#                                     'time_type': 'day',
#                                     'sql': uku_oldmodelv2_var_sql.ONEKEYLOAN_VAR_SQL,
#                                     'recipients': ['fangmingqing@mintechai.com','yantingting@mintechai.com']
#                                   },
#                     'weekly_param': {'obs_window': 4,
#                                      'per_window': 0,
#                                      'time_type': 'week',
#                                      'sql': uku_oldmodelv2_var_sql.VAR_SQL,
#                                      'recipients': ['fangmingqing@mintechai.com','yantingting@mintechai.com']
#                                     },
#                     'performance_param': { 'obs_window': 15,
#                                     'per_window': 21,
#                                     'time_type': 'day',
#                                     'sql': uku_oldmodelv2_var_sql.PER_SQL,
#                                     'time_cols': 'effective_date',
#                                     'flag': 'ever7',
#                                     'label': 'dpd7+',
#                                     'recipients': ['fangmingqing@mintechai.com','yantingting@mintechai.com']
#                                 },
#                     'file_name': '/home/ops/repos/analysis/cron/alert/excel/UKU_OldUserModelV2.xlsx',
#                     'report_path': '/home/ops/repos/analysis/cron/alert/excel/eda/uku_old_model_v2/',
#                     'eda_name': '02_EDA_ONEKEYLOAN',
#                     'dist_name': '03_distribution_ONEKEYLOAN',
#                     'perftable_name': '04_performance',
#                 },
#         "UKU_A_OLDMODELV2_MODIFY": {'product_name' :'uku_modify',
#                     'model_name' : 'oldusermodelv2',
#                     'daily_param': {'obs_window': 30,
#                                     'per_window': 0,
#                                     'time_type': 'day',
#                                     'sql': uku_oldmodelv2_var_sql.MODIFY_VAR_SQL,
#                                     'recipients': ['fangmingqing@mintechai.com','yantingting@mintechai.com']
#                                   },
#                     'weekly_param': {'obs_window': 4,
#                                      'per_window': 0,
#                                      'time_type': 'week',
#                                      'sql': uku_oldmodelv2_var_sql.MODIFY_VAR_SQL,
#                                      'recipients': ['fangmingqing@mintechai.com','yantingting@mintechai.com']
#                                     },
#                     'performance_param': {
#                                     'obs_window': 15,
#                                     'per_window': 21,
#                                     'time_type': 'day',
#                                     'sql': uku_oldmodelv2_var_sql.PER_SQL,
#                                     'time_cols': 'effective_date',
#                                     'flag': 'ever7',
#                                     'label': 'dpd7+',
#                                     'recipients': ['fangmingqing@mintechai.com','yantingting@mintechai.com']
#                                 },
#                     'file_name': '/home/ops/repos/analysis/cron/alert/excel/UKU_OldUserModelV2.xlsx',
#                     'report_path': '/home/ops/repos/analysis/cron/alert/excel/eda/uku_old_model_v2/',
#                     'eda_name': '02_EDA_MODIFY',
#                     'dist_name': '03_distribution_MODIFY',
#                     'perftable_name': '04_performance',
#                 },
# '''
